CREATE DATABASE IF NOT EXISTS HACKATHON;
USE HACKATHON;

DROP TABLE IF EXISTS COUPONS;
DROP TABLE IF EXISTS DONATION;
DROP TABLE IF EXISTS PARTNER;
DROP TABLE IF EXISTS DONATOR;
DROP TABLE IF EXISTS USERS;

CREATE TABLE USERS(
	NAME		VARCHAR(150),
	USERNAME	VARCHAR(150) PRIMARY KEY,
	PASSWORD	TEXT NOT NULL,
	EMAIL		VARCHAR(200) UNIQUE NOT NULL
);

CREATE TABLE DONATOR(
	ID_DONATOR	INT PRIMARY KEY AUTO_INCREMENT,
	DONATOR		VARCHAR(150) NOT NULL,
	EMAIL		VARCHAR(200) NOT NULL,
	CPF			CHAR(11) UNIQUE,
	RG			CHAR(9) UNIQUE
);

CREATE TABLE PARTNER(
	COMPANY_NAME	VARCHAR(100),
	COMPANY			VARCHAR(100) PRIMARY KEY,
	WEB_ADDRESS		VARCHAR(300),
	RESPONSIBLE		VARCHAR(150),
	EMAIL			VARCHAR(200)
);

CREATE TABLE DONATION(
	ID_DONATION	INT PRIMARY KEY AUTO_INCREMENT,
	ID_DONATOR 	INT NOT NULL,
	DT_DONATION	DATE,
	COMPANY		VARCHAR(100) NOT NULL,
	VALUE		DOUBLE(30,2),
	CONFIRMED   BIT,
	FOREIGN KEY (ID_DONATOR) REFERENCES DONATOR (ID_DONATOR),
	FOREIGN KEY (COMPANY) REFERENCES PARTNER (COMPANY)
);

CREATE TABLE COUPONS(
    COMPANY		VARCHAR(100) NOT NULL,
    COUPON_ID	TEXT UNIQUE NOT NULL,
    FOREIGN KEY (COMPANY) REFERENCES PARTNER (COMPANY)
);