CREATE DEFINER=`monty`@`%` PROCEDURE `CONFIRM_DONATION`(
IN P_CPF			CHAR(11),
IN P_VALUE			DOUBLE(30,2),			
OUT P_IDDONATOR		INT,
OUT P_COUPONID		TEXT
)
BEGIN
	DECLARE V_IDDONATION INT;
    DECLARE V_COMPANY    VARCHAR(100);
    
    SELECT ID_DONATOR
		INTO P_IDDONATOR
        FROM DONATOR WHERE CPF = P_CPF;

	SELECT ID_DONATION, COMPANY
		INTO V_IDDONATION, V_COMPANY
        FROM DONATION WHERE(
			SELECT MAX(ID_DONATION) FROM DONATION WHERE ID_DONATOR = P_IDDONATOR AND CONFIRMED = 0) = ID_DONATION;

    UPDATE DONATION SET DT_DONATION = SYSDATE(), CONFIRMED = 1, VALUE = P_VALUE
		WHERE ID_DONATION = V_IDDONATION;
    
    COMMIT;
    
     CALL CONSUME_COUPON(V_COMPANY, P_COUPONID);
END