CREATE DEFINER=`monty`@`%` PROCEDURE `CONSUME_COUPON`(
IN P_COMPANY		CHAR(100),		
OUT P_COUPONID		TEXT
)
BEGIN
	IF (SELECT COUNT(1) FROM COUPONS WHERE COMPANY = P_COMPANY < 1)
		THEN
        SIGNAL SQLSTATE '12412' SET MESSAGE_TEXT = 'Não há mais cupons disponíveis';
	END IF;
    
    SELECT COUPON_ID
		INTO P_COUPONID
        FROM COUPONS WHERE COMPANY = P_COMPANY LIMIT 1;

	DELETE FROM COUPONS WHERE COUPON_ID = P_COUPONID;
    COMMIT;
END