CREATE DEFINER=`monty`@`%` PROCEDURE `NEW_DONATION`(
IN P_COMPANY		VARCHAR(100),
IN P_DONATOR		VARCHAR(150),
IN P_EMAIL	  		VARCHAR(200),
IN P_CPF	  		CHAR(11),
IN P_RG	  			CHAR(9),
OUT P_IDDONATION	INT,
OUT P_IDDONATOR		INT
)
BEGIN
	DECLARE V_EXISTE INT;
    
    SELECT COUNT(1) 
		INTO V_EXISTE
        FROM DONATOR WHERE DONATOR = P_DONATOR AND CPF = P_CPF;
    
	IF (SELECT COUNT(1) FROM DONATOR WHERE CPF = P_CPF AND RG = P_RG) <> V_EXISTE
		THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Há divergência de informações';
	ELSE
		IF (V_EXISTE) = 0
			THEN
            INSERT INTO DONATOR (DONATOR, EMAIL, CPF, RG)
				VALUES (P_DONATOR, P_EMAIL, P_CPF, P_RG);
			SELECT ID_DONATOR
				INTO P_IDDONATOR
				FROM DONATOR WHERE DONATOR = P_DONATOR AND CPF = P_CPF AND IFNULL(RG,0) = IFNULL(P_RG,0) AND EMAIL = P_EMAIL;
                
                IF P_IDDONATOR IS NULL 
					THEN 
                    ROLLBACK;
					SIGNAL SQLSTATE '43333' SET MESSAGE_TEXT = 'Não foram informados campos obrigatórios';
				END IF;
		ELSE
			SELECT ID_DONATOR
				INTO P_IDDONATOR
				FROM DONATOR WHERE CPF = P_CPF;
                
			UPDATE DONATOR SET EMAIL = P_EMAIL, RG = P_RG
				WHERE ID_DONATOR = P_IDDONATOR;
		END IF;
	END IF;
	
    INSERT INTO DONATION (ID_DONATOR, COMPANY, DT_DONATION, CONFIRMED)
		VALUES (P_IDDONATOR, P_COMPANY, SYSDATE(), 0);

    COMMIT;
    
    SELECT ID_DONATION
		INTO P_IDDONATION
        FROM DONATION WHERE(
			SELECT MAX(DT_DONATION) FROM DONATION WHERE ID_DONATOR = P_IDDONATOR AND COMPANY = P_COMPANY AND CONFIRMED = 0);
	
END